version: 2

models:
  - name: int_orders_enriched
    description: Enriched order data with calculated metrics and aggregations
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - unique
          - not_null
          
      - name: customer_id
        description: Customer who placed the order
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
              
      - name: customer_unique_id
        description: Unique customer identifier across all customer records
        
      - name: customer_city
        description: City of the customer
        
      - name: customer_state
        description: State of the customer
        
      - name: order_status
        description: Current status of the order
        tests:
          - accepted_values:
              values: ['delivered', 'shipped', 'processing', 'canceled', 'unavailable', 'invoiced', 'created', 'approved']
              
      - name: order_purchase_timestamp
        description: Timestamp when the order was placed
        
      - name: order_approved_at
        description: Timestamp when the order was approved
        
      - name: order_delivered_carrier_date
        description: Date when the order was delivered to carrier
        
      - name: order_delivered_customer_date
        description: Date when the order was delivered to customer
        
      - name: order_estimated_delivery_date
        description: Estimated delivery date
        
      - name: hours_to_approval
        description: Hours between order placement and approval
        
      - name: days_to_carrier
        description: Days between order approval and delivery to carrier
        
      - name: days_in_transit
        description: Days between carrier pickup and customer delivery
        
      - name: total_delivery_days
        description: Total days from order placement to customer delivery
        
      - name: days_early_late
        description: Days early (negative) or late (positive) compared to estimated delivery
        
      - name: delivery_status
        description: Delivery status (on_time, late, pending)
        
      - name: item_count
        description: Number of items in the order
        
      - name: total_item_price
        description: Total price of all items in the order
        
      - name: total_freight_value
        description: Total freight value for the order
        
      - name: total_order_value
        description: Total order value including items and freight
        tests:
          - not_null
          
      - name: payment_count
        description: Number of payments for the order
        
      - name: total_payment_value
        description: Total payment value for the order
        
      - name: has_credit_card
        description: Whether the order includes credit card payment
        
      - name: has_boleto
        description: Whether the order includes boleto payment
        
      - name: has_voucher
        description: Whether the order includes voucher payment
        
      - name: has_debit_card
        description: Whether the order includes debit card payment
          
  - name: int_products_enriched
    description: Enriched product data with sales and review metrics
    columns:
      - name: product_id
        description: Unique product identifier
        tests:
          - unique
          - not_null
          
      - name: product_category_name
        description: Product category name in Portuguese
        
      - name: product_category_name_english
        description: Product category name in English
        
      - name: product_name_length
        description: Length of the product name
        
      - name: product_description_length
        description: Length of the product description
        
      - name: product_photos_quantity
        description: Number of product photos
        
      - name: product_weight_grams
        description: Product weight in grams
        
      - name: product_length_cm
        description: Product length in centimeters
        
      - name: product_height_cm
        description: Product height in centimeters
        
      - name: product_width_cm
        description: Product width in centimeters
        
      - name: product_volume_cm3
        description: Product volume in cubic centimeters
        
      - name: total_orders
        description: Total number of orders containing this product
        
      - name: total_revenue
        description: Total revenue generated by this product
        
      - name: avg_price
        description: Average price of this product
        
      - name: total_freight
        description: Total freight cost for this product
        
      - name: avg_freight
        description: Average freight cost for this product
        
      - name: review_count
        description: Number of reviews for this product
        
      - name: avg_review_score
        description: Average review score for this product
        
      - name: five_star_count
        description: Number of 5-star reviews
        
      - name: one_star_count
        description: Number of 1-star reviews
        
      - name: quality_score
        description: Quality score based on reviews (only if review count >= 10)
        
  - name: int_customers_enriched
    description: Enriched customer data with lifetime metrics
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
          
      - name: customer_unique_id
        description: Unique customer identifier across all customer records
        
      - name: customer_zip_code_prefix
        description: Customer zip code prefix
        
      - name: customer_city
        description: Customer city
        
      - name: customer_state
        description: Customer state
        
      - name: total_orders
        description: Total number of orders placed by customer
        
      - name: lifetime_value
        description: Total lifetime value of customer
        
      - name: avg_order_value
        description: Average order value for customer
        
      - name: first_order_date
        description: Date of first order
        
      - name: last_order_date
        description: Date of last order
        
      - name: avg_delivery_days
        description: Average delivery days for customer orders
        
      - name: delivered_orders
        description: Number of delivered orders
        
      - name: canceled_orders
        description: Number of canceled orders
        
      - name: late_deliveries
        description: Number of late deliveries
        
      - name: customer_tenure_days
        description: Days between first and last order
        
      - name: customer_segment
        description: Customer segmentation based on purchase behavior
        tests:
          - accepted_values:
              values: ['loyal', 'repeat', 'one_time']
              
      - name: value_segment
        description: Customer value segmentation (high_value, medium_value, low_value)
        
      - name: late_delivery_rate
        description: Rate of late deliveries for this customer
              
  - name: int_sellers_enriched
    description: Enriched seller data with sales, review, and delivery performance metrics
    columns:
      - name: seller_id
        description: Unique seller identifier
        tests:
          - unique
          - not_null
          
      - name: seller_zip_code_prefix
        description: Seller zip code prefix
        
      - name: seller_city
        description: Seller city
        
      - name: seller_state
        description: Seller state
        
      - name: total_orders
        description: Total number of orders fulfilled by seller
        
      - name: total_items_sold
        description: Total number of items sold by seller
        
      - name: total_revenue
        description: Total revenue generated by this seller
        
      - name: avg_item_price
        description: Average item price for seller
        
      - name: total_freight
        description: Total freight charged by seller
        
      - name: avg_freight
        description: Average freight charged by seller
        
      - name: min_item_price
        description: Minimum item price for seller
        
      - name: max_item_price
        description: Maximum item price for seller
        
      - name: review_count
        description: Number of reviews for seller's products
        
      - name: avg_review_score
        description: Average review score for seller's products
        
      - name: five_star_count
        description: Number of 5-star reviews
        
      - name: one_star_count
        description: Number of 1-star reviews
        
      - name: avg_delivery_days
        description: Average delivery days for seller's orders
        
      - name: on_time_deliveries
        description: Number of on-time deliveries
        
      - name: total_delivered_orders
        description: Total number of delivered orders
        
      - name: on_time_delivery_rate
        description: Rate of on-time deliveries
        
      - name: seller_segment
        description: Seller segmentation based on order volume
        tests:
          - accepted_values:
              values: ['high_volume', 'medium_volume', 'low_volume', 'inactive']
              
      - name: revenue_segment
        description: Revenue segment classification
        
      - name: quality_score
        description: Quality score based on reviews (only if review count >= 10)
