version: 2

models:
  - name: int_orders_enriched
    description: Enriched order data with calculated metrics and aggregations
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - unique
          - not_null
          
      - name: customer_id
        description: Customer who placed the order
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
              
      - name: order_status
        description: Current status of the order
        tests:
          - accepted_values:
              values: ['delivered', 'shipped', 'processing', 'canceled', 'unavailable', 'invoiced', 'created', 'approved']
              
      - name: total_order_value
        description: Total order value including items and freight
        tests:
          - not_null
          
  - name: int_products_enriched
    description: Enriched product data with sales and review metrics
    columns:
      - name: product_id
        description: Unique product identifier
        tests:
          - unique
          - not_null
          
      - name: total_revenue
        description: Total revenue generated by this product
        
  - name: int_customers_enriched
    description: Enriched customer data with lifetime metrics
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
          
      - name: customer_segment
        description: Customer segmentation based on purchase behavior
        tests:
          - accepted_values:
              values: ['loyal', 'repeat', 'one_time']
